version: 2
updates:
  - package-ecosystem: maven
    directory: /app
    schedule:
      interval: weekly
    groups:
      java-runtime:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      frontend-runtime:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
